### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by mutexlox-signal** [mozilla/cubeb-rs#103]
There are a few notable changes since 0.14.0, including:

* [Fix build on arm64 linux.](https://github.com/mozilla/cubeb-rs/commit/d9be0bfca8f9585c2bfc775083124088fd0370ca)
* [Add build.rs config to use rust backends.](https://github.com/mozilla/cubeb-rs/commit/3d8887f70b0fae18e523a6e867a1e1a5d74af78c)
* [Allow clients to set a log callback.](https://github.com/mozilla/cubeb-rs/commit/eb8eb57b277dc625e8e780824b7f025b445c2f9b)
* [Update libcubeb.](https://github.com/mozilla/cubeb-rs/commit/e931eec8e102f547fc8cb27041caa00f1aa07eac)
  * pulls in crash fix for cubeb-coreaudio-rs

Could you please cut a release to crates.io to pick up these changes? (Potentially with https://github.com/mozilla/cubeb-rs/pull/101, if you'd like to grab that too.)

cc @padenot

**Comment by mutexlox-signal** [comment]
just wanted to bump this up and see if you could make a new release with the latest changes? (cc @padenot @kinetiknz )

thanks!

**Comment by kinetiknz** [comment]
I've released 0.15 now.

I had to tweak the `cubeb-sys` build in https://github.com/mozilla/cubeb-rs/pull/104 to disable libcubeb Rust builds when building the packaged crate, because the packaged source is not a git repository so `git submodule` commands do nothing and we're unable to update the libcubeb or cubeb-*-rs trees.
