### ISSUE TITLE
Extending CI with macOS, windows (possibly also rustfmt, auto-publish, clippy suggestions)

### ISSUE THREAD

**Issue by mitchmindtree** [mozilla/cubeb-rs#48]
I noticed there is already some CI setup for testing on Linux [here](https://github.com/djg/cubeb-rs/blob/master/.circleci/config.yml). I thought it might be worth opening an issue for testing on other platforms and adding some other handy tools to the CI process.

Recently [CPAL](https://github.com/RustAudio/cpal) switched their CI from a combination of travis, appveyor and circle-ci to use Github workflows. I'm still a little new to the way they work, but one nice benefit seems to be that each of the main platforms are supported in one place. You can find CPAL's workflow [here](https://github.com/RustAudio/cpal/blob/master/.github/workflows/cpal.yml) where the following jobs are specified:

- `clippy-test`: runs clippy on the repo providing good-practise suggestions to contributors (though addressing each isn't a necessity for landing PRs).
- `rustfmt-check`: checks PRs have been formatted with the current stable rustfmt with default settings.
- `cargo-publish`: automatically publishes new releases of crates within the CPAL repository to crates.io when a PR is merged into master as long as 1. all CI passed successfully and 2. the version in the Cargo.toml has been updated. Something like this might ease the pain-point mentioned [here](https://github.com/kinetiknz/cubeb/issues/467#issuecomment-431512934) and make it easier to keep the `cubeb*` crates up to date on crates.io.
- `ubuntu-test`
- `asmjs-wasm32-test`
- `windows-test`
- `macos-test`

I should mention that while it's convenient to have all CI in one place like this, it comes with the downfall of being a little more tied down to Github. Then again, I suppose it is not too tricky to switch to a different service in the case that the repository is moved, and this workflow could be used as a reference assisting in the process.

Would you be interested in a PR that adds a workflow with jobs similar to those above?

**Comment by kinetiknz** [comment]
That sounds great, thank you.  The current CircleCI setup we've got here tends to break easily and is painful to manage due to requiring Docker image rebuilds to update the build environment.  Improvements are definitely welcome!

Do you know if the GitHub workflow instances have working audio (hardware or dummy drivers) on various platforms? We run a restricted set of tests in the current cubeb repos due to a lack of audio hardware in the CI instances and have been leaning on Gecko's CI infrastructure for testing, but it's an awkward workflow where it's all to easy to break things upstream and discover them later in the Gecko CI.  We had just starting looking at installing dummy audio drivers on Windows Travis to help with this, so if the GitHub workflow instances work out of the box that's a huge win.

**Comment by kinetiknz** [comment]
CI builds on Linux/macOS/Windows now, with rustfmt and clippy integration.  I'll mark this as done.
